# Generated by Django 5.1.1 on 2024-10-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unit_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='Temp-code', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
